modLoader="javafml"
loaderVersion="[37,)"
license="LGPL-3.0"
issueTrackerURL = "https://github.com/Janoeo/World/issues"

[[mods]]
modId="janoeo_world"
version="${file.jarVersion}"
displayName="Janoeo World"
logoFile="janoeo_world.png"
itemIcon="janoeo_world:cherry_sapling"
displayURL="https://www.curseforge.com/minecraft/mc-mods/janoeo-world"
authors="AlasDiablo, lIotaMiu, Safyrus"
credits="Structure builder: Raegann"
description='''
A mod who add structure and more!
'''
[[dependencies.janoeo_world]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_world]]
    modId="diolib"
    mandatory=true
    versionRange="[2.0.17,)"
    ordering="AFTER"
    side="BOTH"