modLoader="javafml"
loaderVersion="[37,)"
license="LGPL-3.0"
[[mods]]
modId="janoeo_world"
version="${file.jarVersion}"
displayName="Janoeo - World"
authors="AlasDiablo, lIotaMiu, Egame257 and Safyrus"
description='''
Janoeo - World by AlasDiablo, lIotaMiu, Egame257 and Safyrus
'''
[[dependencies.janoeo_world]]
    modId="forge"
    mandatory=true
    versionRange="[37,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_world]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1,1.18)"
    ordering="NONE"
    side="BOTH"
[[dependencies.janoeo_world]]
    modId="diolib"
    mandatory=true
    versionRange="[2.0.17,)"
    ordering="AFTER"
    side="BOTH"